## Linear Algebra Final Project - Ruggiero Julian

### Part 1: Solve a system of equations
Set up a system of equations with 3 variables and 3 constraints and solve for x.

The function to solve will be the form __Ax = b__

$$\begin{array}{lrcrcrcr}
        2x_{1} & + & 1x_{2} & + & 1x_{3} & = & 4 \\
        1x_{1} & + & 3x_{2} & + & 0x_{3} & = & 5 \\
        1x_{1} & + & 2x_{2} & + & 0x_{3} & = & 6
\end{array}$$

In [1]:
import numpy as np
# define matrix A
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 

# define vector solution b
b=[4, 5, 6]

In [2]:
#transform b to get the same dimensions as A to concatenate
B = np.array([b]) 

#transpose B and concatenate to A
A=np.concatenate((A, B.T), axis=1)

In [3]:
A

array([[2, 1, 1, 4],
       [1, 3, 2, 5],
       [1, 0, 0, 6]])

In [4]:
#define row1, row2 and row3
row1=A[0]
row2=A[1]
row3=A[2]

#to work easier in the code, define the corresponding 'a' elements
a11,a12,a13,a14=row1
a21,a22,a23,a24=row2
a31,a32,a33,a34=row3

# start Gauss elimination
# create scalar (-1/2) to multiply row1 and add to row2
scalar_row2=-a21/a11
row=row1 * scalar_row2
row2=row+row2
a21,a22,a23,a24=row2

print('Scalar: ', scalar_row2)
print('New row 2  \n', row2)

Scalar:  -0.5
New row 2  
 [0.  2.5 1.5 3. ]


In [5]:
# create scalar (-1/2) to multiply row1 and add to row3
scalar_row3=-a31/a11
row=row1 * scalar_row3
row3=row+row3
a31,a32,a33,a34=row3

print('Scalar: ', scalar_row3)
print('New row 3  \n', row3)

Scalar:  -0.5
New row 3  
 [ 0.  -0.5 -0.5  4. ]


Up to now the system of equations looks like this:

$$\begin{array}{lrcrcrcr}
        2x_{1} & + & 1x_{2} & + & 1x_{3} & = & 4 \\
        0x_{1} & + & 2.5x_{2} & + & 1.5x_{3} & = & 3 \\
        0x_{1} & - & 0.5x_{2} & - & 0.5x_{3} & = & 4
\end{array}$$

Now we need to get a zero in the a32 element, so the scalar to multiply row2 is __1/5__ and add to row 3.

In [6]:
# create scalar to multiply row2 and add to row3
scalar_row3=-a32/a22
row=row2 * scalar_row3
row3=row+row3
a31,a32,a33,a34=row3

print('Scalar: ', scalar_row3)
print('New row 3  \n', row3)

Scalar:  0.2
New row 3  
 [ 0.   0.  -0.2  4.6]


The system looks like this now:

$$\begin{array}{lrcrcrcr}
        2x_{1} & + & 1x_{2} & + & 1x_{3} & = & 4 \\
        0x_{1} & + & 2.5x_{2} & + & 1.5x_{3} & = & 3 \\
        0x_{1} & + & 0x_{2} & - & 0.2x_{3} & = & 4.6
\end{array}$$

Using back substitution:

In [7]:
#get results, back substitution
x3=a34/a33
x2=(a24-(a23*x3))/a22
x1=(a14-(a13*x3)-(a12*x2))/a11

print('x1=', round(x1,2),', x2=', round(x2,2),', x3=', round(x3,2))

x1= 6.0 , x2= 15.0 , x3= -23.0


### Part 2: Write a function and solve using elimination
Write a function in python that will take two variables (matrix A & constraint vector b) and solve using elimination. Your function should produce the right answer for the system of equations for any 3-variable, 3-equation system.

You don’t have to worry about degenerate cases and can safely assume that the function will only be tested with a system of equations that has a solution. Nor do you have to worry about zero pivots.

Do not use the built-in function solver to solve this system or use matrix inverses. The approach that you should employ is to construct an Upper Triangular Matrix and then back-substitute to get the solution.  Alternatively, you can augment the matrix A with vector b and jointly apply the Gauss Jordan elimination procedure.

Please then submit two test equations to show that your approach works.

In [8]:
def solve_3_x_3(A,b):
    """This function takes a 3x3 matrix and the solution vector b
    and solve to find x1,x2,x3 using Gauss elimination and back substitution.
    I make the assumption that the matrix received is a 3x3"""
    
    #transform b to get the same dimensions as A to concatenate
    B = np.array([b]) 
    
    #transpose B and concatenate to A
    A=np.concatenate((A, B.T), axis=1)
    
    #check if swap rows is needed
    if(A[0,0]==0):
        A=swap_rows(A)
    
    #define row1, row2 and row3
    row1=A[0]
    row2=A[1]
    row3=A[2]
    
    #to work easier in the code, define the corresponding 'a' elements
    a11,a12,a13,a14=row1
    a21,a22,a23,a24=row2
    a31,a32,a33,a34=row3
    
    # start Gauss elimination, check if first element in row 3 is not zero
    if(a21!=0):
        
        # create scalar to multiply row1 and add to row2
        scalar_row2=-a21/a11
        row=row1 * scalar_row2
        row2=row+row2
        a21,a22,a23,a24=row2
        
    #check if first element in row 3 is not zero
    if(a31!=0):
        
        # create scalar to multiply row1 and add to row3
        scalar_row3=-a31/a11
        row=row1 * scalar_row3
        row3=row+row3
        a31,a32,a33,a34=row3
        
    #check if second element in row 3 is not zero
    if(a32!=0):
        
        # create scalar to multiply row2 and add to row3
        scalar_row3=-a32/a22
        row=row2 * scalar_row3
        row3=row+row3
        a31,a32,a33,a34=row3
    
    #get results, back substitution
    x3=a34/a33
    x2=(a24-(a23*x3))/a22
    x1=(a14-(a13*x3)-(a12*x2))/a11
    
    return np.array([x1, x2, x3])

In [9]:
def swap_rows(A):
    
    """Function that gets a matrix A that need a row swap 
    because of a zero in the first element"""
    
    row1=A[0]
    row2=A[1]
    row3=A[2]
    
    a11,a12,a13,a14=row1
    a21,a22,a23,a24=row2
    a31,a32,a33,a34=row3
    
    if(a12 != 0):
        #swap row1 and row2
        row1,row2=row2,row1
        return np.array([row1, row2, row3])

    if(a13 != 0):
        #swap row1 and row3
        row1,row3=row3,row1
        return np.array([row1, row2, row3])

__Test case 1__

In [10]:
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 
b=[4, 5, 6]
solve_3_x_3(A,b)

array([  6.,  15., -23.])

__Test case 2__

In [11]:
A=np.array([[2,12,17],[-3,-7,-8],[1,4,6]])
b=[-32, 6, -7]
solve_3_x_3(A,b)

array([ 9., -7.,  2.])

In [12]:
A = np.array([[2,-3,0],[4,-5,1],[2,-1,-3]]) 
b=[3, 7, 5]
solve_3_x_3(A,b)

array([ 3.,  1., -0.])

In [13]:
#checking with prebuilt functions
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 
#define matrix B 
B = np.array([4, 5, 6]) 
# linalg.solve is the function of NumPy to solve a system of linear scalar equations 
print ("Solutions:\n",np.linalg.solve(A, B ) )
#Solutions: [ 6. 15. -23.]

Solutions:
 [  6.  15. -23.]


In [14]:
A=np.array([[2,12,17],[-3,-7,-8],[1,4,6]])
B = np.array([-32, 6, -7]) 
print ("Solutions:\n",np.linalg.solve(A, B ) )

Solutions:
 [ 9. -7.  2.]


### Part 3: Functions of matrices

Show that $\pmb A^TA$ does not equal $\pmb AA^T$ in general

For a special type of square matrix A, we get $\pmb A^TA$ = $\pmb AA^T$. Under what conditions could this be true? (Hint: The Identity matrix I is an example of such a matrix).

I will have a function check_dot_prod_with_t() that verifies this condition.

In [15]:
def check_dot_prod_with_t(A):
    """Receives a square matrix as a parameter and checks if 
    if A dot product Transpose = Transpose dot product A"""
    
    #get the transpose
    transpose=A.T
    
    #dot product between transpose and A
    ATdotA=np.dot(transpose,A)
    
    #dot product between A and its transpose 
    AdotAT=np.dot(A,transpose)
    
    #if the 2 dot products are equal, return true, else false
    return np.array_equal(ATdotA, AdotAT)

In [16]:
#check for a random 2x2 matrix
A = np.array([[2, 8], [3, 4]]) 
check_dot_prod_with_t(A)

False

In [17]:
#check with identity matrix
A = np.array([[1, 0], [0, 1]]) 
check_dot_prod_with_t(A)

True

For this condition to apply, the square matrix has to be symetric. As mentioned above the Identity matrix is an example. 

In [18]:
#check for a new 2x2
A = np.array([[2, 8], [8, 2]]) 
check_dot_prod_with_t(A)

True

In [19]:
#define other square symetric matrix
A = np.array([[3, -2, 4], [-2, 6, 2], [4, 2, 3]]) 
check_dot_prod_with_t(A)

True

### Part 4: Matrix factorization

Matrix factorization is a very important problem. There are supercomputers built just to do matrix factorizations. Every second you are on an airplane, matrices are being factorized. Radars that track flights use a technique called Kalman filtering. At the heart of Kalman Filtering is a Matrix Factorization operation. Kalman Filters are solving linear systems of equations when they track your flight using radars.

Write a python function to factorize a square matrix A into LU or LDU, whichever you prefer. Assume that the matrix size is less than 5 by 5.

##### Important note

Solution for part 2 did not use any for loop and is fixed to a 3x3 matrix. Now I need to solve for 2x2 and 4x4, so I will create similar functions to handle these new cases and depending on the size of the incoming matrix the general function __get_LU_decomposition()__ will execute the one that applies to that matrix size.

In [20]:
def get_LU_decomposition(A):
    """Checks the matrix size and calls the corresponding function"""
    
    if len(A) == 2:
        return get_U_decomposition_2_x_2(A)
    
    if len(A) == 3:
        return get_U_decomposition_3_x_3(A)
    
    if len(A) == 4:
        return get_U_decomposition_4_x_4(A)

In [21]:
#THIS ONE RETURNS THE UPPER MATRIX "U", and the coefficients to place and create the L
def get_U_decomposition_2_x_2(A):
    """THIS ONE RETURNS THE UPPER MATRIX 'U', and the coefficients to place and create the L
    for a 2x2 matrix"""
    
    #define a list to collect the coefficients that helps in the Gauss elimination
    scalars=[]
    
    #check if swap rows is needed
    if(A[0,0]==0):
        A=swap_rows(A)
    
    #define row1, row2 and row3
    row1=A[0]
    row2=A[1]
    
    #to work easier in the code and avoid confusion that python starts at zero position 
    #we define the corresponding 'a' elements
    a11,a12=row1
    a21,a22=row2
    
    # start Gauss elimination, check if first element in row 2 is not zero
    if(a21!=0):
        
        # create scalar to multiply row1 and add to row2
        scalar=-a21/a11
        row=row1 * scalar
        row2=row+row2
        a21,a22=row2
        scalars.append(scalar*-1)
        print(scalar)
      
    #return upper matrix U and the coefficients to create lower matrix L
    return np.array([row1, row2]), scalars

In [22]:
A = np.array([[2, 1], [1, 3]]) 
result=get_LU_decomposition(A)
result

-0.5


(array([[2. , 1. ],
        [0. , 2.5]]), [0.5])

In [23]:
#THIS ONE RETURNS THE UPPER MATRIX "U", and the coefficients to place and create the L
def get_U_decomposition_3_x_3(A):
    """THIS ONE RETURNS THE UPPER MATRIX 'U', and the coefficients to place and create the L
    for a 3x3 matrix"""
    
    #define a list to collect the coefficients that helps in the Gauss elimination
    scalars=[]
    
    #check if swap rows is needed
    if(A[0,0]==0):
        A=swap_rows(A)
    
    #define row1, row2 and row3
    row1=A[0]
    row2=A[1]
    row3=A[2]
    
    #to work easier in the code and avoid confusion that python starts at zero position 
    #we define the corresponding 'a' elements
    a11,a12,a13=row1
    a21,a22,a23=row2
    a31,a32,a33=row3
    
    # start Gauss elimination, check if first element in row 2 is not zero
    if(a21!=0):
        
        # create scalar to multiply row1 and add to row2
        scalar=-a21/a11
        row=row1 * scalar
        row2=row+row2
        a21,a22,a23=row2
        scalars.append(scalar*-1)
        print(scalar)
        
    #check if first element in row 3 is not zero
    if(a31!=0):
        
        # create scalar to multiply row1 and add to row3
        scalar=-a31/a11
        row=row1 * scalar
        row3=row+row3
        a31,a32,a33=row3
        scalars.append(scalar*-1)
        print(scalar)
        
    #check if second element in row 3 is not zero
    if(a32!=0):
        
        # create scalar to multiply row2 and add to row3
        scalar=-a32/a22
        row=row2 * scalar
        row3=row+row3
        a31,a32,a33=row3
        scalars.append(scalar*-1)
        print(scalar)
      
    #return upper matrix U and the coefficients to create lower matrix L
    return np.array([row1, row2, row3]), scalars

Testing for function __get_U_decomposition_3_x_3(A)__

In [24]:
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 
result=get_LU_decomposition(A)
result

-0.5
-0.5
0.2


(array([[ 2. ,  1. ,  1. ],
        [ 0. ,  2.5,  1.5],
        [ 0. ,  0. , -0.2]]), [0.5, 0.5, -0.2])

In [25]:
U=result[0]
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [26]:
#to create L we can start with an identity matrix
L=np.eye(3)

#fill the identity with the corresponding coefficients to get the lower matrix L
L[1,0]=result[1][0]
L[2,0]=result[1][1]
L[2,1]=result[1][2]
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [27]:
# verify with dot product that LU = A
dot=np.dot(L,U)
dot

array([[ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00, -2.77555756e-17,  2.77555756e-17]])

In [28]:
# Verify same matrix A with python prebuilt library scipy.linalg
import scipy.linalg as linalg
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 
P, L, U = linalg.lu(A) 
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [29]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [30]:
np.dot(L,U)

array([[ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00, -2.77555756e-17,  0.00000000e+00]])

__LU Decomposition for a 4x4__

In [31]:
#THIS ONE RETURNS THE UPPER MATRIX "U", and the coefficients to place and create the L
def get_U_decomposition_4_x_4(A):
    """THIS ONE RETURNS THE UPPER MATRIX 'U', and the coefficients to place and create the L
    for a 4x4 matrix"""
    
    #define a list to collect the coefficients that helps in the Gauss elimination
    scalars=[]
     
    #define row1, row2, row3 and row4
    row1=A[0]
    row2=A[1]
    row3=A[2]
    row4=A[3]
    
    #to work easier in the code, define the corresponding 'a' elements
    a11,a12,a13,a14=row1
    a21,a22,a23,a24=row2
    a31,a32,a33,a34=row3
    a41,a42,a43,a44=row4
    
    # start Gauss elimination
    #check if first element in row 2 is not zero
    if(a21!=0):
        
        # create scalar to multiply row1 and add to row2
        scalar=-a21/a11
        row=row1 * scalar
        row2=row+row2
        
        #refresh new values 
        a21,a22,a23,a24=row2
        
        #append the scalar that was used as multiplier to create the lower matrix L
        scalars.append(scalar*-1)
    else:
        #in case that the position is already zero, 
        #store a 0.0 to then place this in the correct position in the L matrix
        scalars.append(0.0)
        
    #check if first element in row 3 is not zero
    if(a31!=0):
        
        # create scalar to multiply row1 and add to row3
        scalar=-a31/a11
        row=row1 * scalar
        row3=row+row3
        a31,a32,a33,a34=row3
        scalars.append(scalar*-1)
    else:
        scalars.append(0.0)
        
    #check if first element in row 4 is not zero
    if(a41!=0):
        
        # create scalar to multiply row1 and add to row3
        scalar=-a41/a11
        row=row1 * scalar
        row4=row+row4
        a41,a42,a43,a44=row4
        scalars.append(scalar*-1)
    else:
        scalars.append(0.0)
        
    #check if second element in row 3 is not zero
    if(a32!=0):
        
        # create scalar to multiply row2 and add to row3
        scalar=-a32/a22
        row=row2 * scalar
        row3=row+row3
        a31,a32,a33=row3
        scalars.append(scalar*-1)
    else:
        scalars.append(0.0)
    
    #check if second element in row 4 is not zero
    if(a42!=0):
        
        # create scalar to multiply row2 and add to row3
        scalar=-a42/a22
        row=row2 * scalar
        row4=row+row4
        a41,a42,a43,a44=row4
        scalars.append(scalar*-1)
    else:
        scalars.append(0.0)
        
    #check if third element in row 4 is not zero
    if(a43!=0):
        
        # create scalar to multiply row2 and add to row3
        scalar=-a43/a33
        row=row3 * scalar
        row4=row+row4
        a41,a42,a43,a44=row4
        scalars.append(scalar*-1)
    else:
        scalars.append(0.0)
     
    #return upper matrix U and the coefficients to create lower matrix L
    return np.array([row1, row2, row3, row4]), scalars

In [32]:
def swap_rows_4x4(A):
    row1=A[0]
    row2=A[1]
    row3=A[2]
    row4=A[3]
    
    a11,a12,a13,a14,a15=row1
    a21,a22,a23,a24,a25=row2
    a31,a32,a33,a34,a35=row3
    a41,a42,a43,a44,a45=row4
    
    if(a12 != 0):
        #swap row1 and row2
        row1,row2=row2,row1
        return np.array([row1, row2, row3])

    if(a13 != 0):
        #swap row1 and row3
        row1,row3=row3,row1
        return np.array([row1, row2, row3])

Testing for function __get_U_decomposition_4_x_4(A)__

In [33]:
A=np.array([[1,-2,-2,-3],[3,-9,0,-9],[-1,2,4,7],[-3,-6,26,2]])
result=get_LU_decomposition(A)
result

(array([[ 1., -2., -2., -3.],
        [ 0., -3.,  6.,  0.],
        [ 0.,  0.,  2.,  4.],
        [ 0.,  0.,  0.,  1.]]), [3.0, -1.0, -3.0, 0.0, 4.0, -2.0])

In [201]:
U=result[0]
U

array([[ 1., -2., -2., -3.],
       [ 0., -3.,  6.,  0.],
       [ 0.,  0.,  2.,  4.],
       [ 0.,  0.,  0.,  1.]])

In [202]:
#to create L we can start with an identity matrix
L=np.eye(4)

#fill the identity with the corresponding coefficients to get the lower matrix L
L[1,0]=result[1][0]
L[2,0]=result[1][1]
L[3,0]=result[1][2]
L[2,1]=result[1][3]
L[3,1]=result[1][4]
L[3,2]=result[1][5]
L

array([[ 1.,  0.,  0.,  0.],
       [ 3.,  1.,  0.,  0.],
       [-1.,  0.,  1.,  0.],
       [-3.,  4., -2.,  1.]])

In [203]:
#checking that LU = A
np.dot(L,U)

array([[ 1., -2., -2., -3.],
       [ 3., -9.,  0., -9.],
       [-1.,  2.,  4.,  7.],
       [-3., -6., 26.,  2.]])

In [204]:
A

array([[ 1, -2, -2, -3],
       [ 3, -9,  0, -9],
       [-1,  2,  4,  7],
       [-3, -6, 26,  2]])

### Part 5: Build your own function to solve a determinant for any matrix
Please test it on one 2 by 2 matrix, one 3 by 3 matrix and one 4 by 4 matrix. Do not use any existing determinant functions

I have two different logics for this exercise, the first one is a method that checks the matrix size and calls the corresponding function, 2x2, 3x3 and 4x4.

The second logic uses recursion, as an ideal solution.

In [205]:
def solve_determinant(A):
    """Square matrix only 2x2, 3x3 or 4x4 and returns its determinant"""
    if len(A) == 2:
        return det_2x2(A)
    elif len(A) == 3:
        return det_3x3(A)
    elif len(A) == 4:
        return det_4x4(A)
    else:
        print("Please insert a 2x2, 3x3, or 4x4 matrix")

In [206]:
def det_2x2(A):
    a1,a2=A[0]
    a3,a4=A[1]
    det=(a1*a4)-(a2*a3)
    return det

In [207]:
def det_3x3(A):
    a11,a12,a13=A[0]
    a21,a22,a23=A[1]
    a31,a32,a33=A[2]
    
    det1=a11*(det_2x2(np.array([[a22,a23],[a32,a33]])))
    det2=-a12*(det_2x2(np.array([[a21,a23],[a31,a33]])))
    det3=a13*(det_2x2(np.array([[a21,a22],[a31,a32]])))
    
    return det1+det2+det3

In [208]:
def det_4x4(A):
    a11,a12,a13,a14=A[0]
    a21,a22,a23,a24=A[1]
    a31,a32,a33,a34=A[2]
    a41,a42,a43,a44=A[3]
    
    det1=a11*(det_3x3(np.array([[a22,a23,a24],[a32,a33,a34],[a42,a43,a44]])))
    det2=-a12*(det_3x3(np.array([[a21,a23,a24],[a31,a33,a34],[a41,a43,a44]])))
    det3=a13*(det_3x3(np.array([[a21,a22,a24],[a31,a32,a34],[a41,a42,a44]])))
    det4=-a14*(det_3x3(np.array([[a21,a22,a23],[a31,a32,a33],[a41,a42,a43]])))
    
    return det1+det2+det3+det4

In [209]:
#test for a 2x2
A=np.array([[12,0],[-3,-7]])
solve_determinant(A)

-84

In [210]:
#check with prebuilt package
linalg.det(A)

-84.0

In [211]:
#test for a 3x3
A=np.array([[4,-1,1],[4,5,3],[-2,0,0]])
solve_determinant(A)

16

In [212]:
#check with prebuilt package
linalg.det(A)

16.0

In [213]:
#test for a 4x4
A=np.array([[4,-1,1,1],[4,5,3,2],[-2,0,0,3],[6,2,8,3]])
solve_determinant(A)

-444

In [214]:
#check with prebuilt package
linalg.det(A)

-443.99999999999994

Other approach: Ideally the solution should be flexible enough to be able to handle any matrix size. Below is a draft of a recursion function, but is not fully working.

In [215]:
def calc_recursive_determinant(A,det,scalar):
    """Recursive function that takes a MxN matrix and calculates its determinant.
    Parameter meaning:
    - A: matrix
    - det: value of the determinant up to this point, initial execution parameter=0
    - scalar: scalar to use to multiply the determinanat result
    """
    #script
    length=len(A)
    if length==2:
        det+=det_2x2(A)*scalar
    else:
        #get top row to use its scalars
        top=A[0]
        
        #remaining of the matrix
        remaining=A[1:]
        
        for i in range(len(A)):
            
            #get each element in the top row to use as a scalar
            if i%2==0:
                scalar=top[i]
            else:
                #multiply by -1 if it is an odd ocurrence
                scalar=top[i]*-1
            
            #prepare a sliced matrix
            matrix=[]
            
            #iterate through the transpose of the remaining to exclude the column in the i'th iteration
            for j,value in enumerate(remaining.T):
                if(i!=j):
                    matrix.append(value)
                    
                    #transpose back to get the appropiate values
                    final_slice = np.array(matrix).T
                    
                    #call the function recursively
                    calc_recursive_determinant(final_slice,det,scalar)
                    
                    
    return det

In [216]:
#test for a 2x2
A=np.array([[12,0],[-3,-7]])
calc_recursive_determinant(A,0,1)

-84

In [217]:
#Recursion is still not working for 3x3
#A=np.array([[4,-1,1],[4,5,3],[-2,0,0]])
#calc_recursive_determinant(A,0,1)

### Part 6: Build your own function from scratch to solve equations via Cramer’s rules.

Please submit 3 examples including at least one 4 by 4 that demonstrates that it works, and do not use any existing shortcut functions. 

In [218]:
def solve_cramer(A,b):
    """Function that takes a matrix A and a solution vector b and solves for 'x'
    computing determinants only based on Cramer's Rule """
    
    #define a vector to store the 'x' elements
    x_vector=[]

    #make a copy of the matrix A
    original_A=np.copy(A)
    
    #get original matrix determinant, using part 5 function
    original_det=solve_determinant(original_A)
    
    #loop through elements in A
    for i in range(len(A)):
        
        #make a new copy of the original matrix
        A=np.copy(original_A)
        
        #substitute the i'th column with the b solution vector
        A[:,i]=b
        
        #get the determinant for the modified matrix
        sub_determinant=solve_determinant(A)
        
        #divide the sub_determinant by the original one and store the result
        x_vector.append(sub_determinant/original_det)
    
    #return 'x' values
    return x_vector

In [219]:
#test for a 2x2
A = np.array([[1,3],[-4,7]])
b = np.array([2,-1])
solve_cramer(A,b)

[0.8947368421052632, 0.3684210526315789]

In [220]:
#verify with prebuilt functions
x = np.dot(linalg.inv(A),b)
print("x:\n",x[:,None])

x:
 [[0.89473684]
 [0.36842105]]


In [221]:
#test for a 3x3
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 
b=np.array([4, 5, 6])
solve_cramer(A,b)

[6.0, 15.0, -23.0]

In [222]:
x = np.dot(linalg.inv(A),b)
print("x:\n",x[:,None])

x:
 [[  6.]
 [ 15.]
 [-23.]]


In [223]:
#test for a 4x4
new_A=np.array([[4,-1,1,1],[4,5,3,2],[-2,0,0,3],[6,2,8,3]])
new_b=np.array([-3, 2, -2, -19])
solve_cramer(new_A,new_b)

[0.6081081081081081,
 1.9504504504504505,
 -3.220720720720721,
 -0.26126126126126126]

In [224]:
x = np.dot(linalg.inv(new_A),new_b)
print("x:\n",x[:,None])

x:
 [[ 0.60810811]
 [ 1.95045045]
 [-3.22072072]
 [-0.26126126]]
